export const componentName = {
	WORKLOAD_PODS: 'WORKLOAD_PODS',
	SERVICES: 'SERVICES',
	SECRETS: 'SECRETS',
	CONFIGMAPS: 'CONFIGMAPS',
	SERVICE_ACCOUNTS: 'SERVICE_ACCOUNTS',
	SERVICES_PODS: 'SERVICES_PODS',
	SERVICES_PODS2: 'SERVICES_PODS2'
};
