FROM nginx:stable-alpine

COPY nginx-devbox.conf /etc/nginx/conf.d/default.conf

COPY apps/devbox/dist/spa /app

RUN apk --no-cache add nginx

RUN ln -sf /dev/stdout /var/log/nginx/access.log && ln -sf /dev/stderr /var/log/nginx/error.log

EXPOSE 80

CMD [ "nginx" ]
