FROM nginx:stable-alpine

WORKDIR /app

RUN sed -i '1idaemon off;' /etc/nginx/nginx.conf

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY ./apps/adminConsole/dist/spa/ ./

EXPOSE 80

CMD ["nginx"]
