export const ROUTE_NAME = {
	GPU_LIST: 'GPU_LIST',
	NETWORK_DETAIL: 'NETWORK_DETAIL',
	PHYSICAL_RESOURCE_DETAIL: 'PHYSICAL_RESOURCE_DETAIL',
	GPUS_DETAILS: 'GPUS_DETAILS',
	TASKS_DETAILS: 'TASKS_DETAILS'
};
