on:
  workflow_call:
    inputs:
      PACKAGE_NAME:
        required: true
        type: string
      PACKAGE_PATH:
        required: true
        type: string
      DOCKERFILE_PATH:
        required: true
        type: string
      DOCKER_CONTEXT:
        type: string
        default: .
      DOCKER_BUILD_ARGS:
        type: string
      DEFAULT_VERSION:
        required: true
        type: string
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v2.1.1
        with:
          file-name: ${{ inputs.PACKAGE_PATH }}

      - name: Update Docker Tag
        id: docker-tag
        run: |
          echo "::set-output name=time::$(TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S')"
          if [ ${{ steps.check.outputs.changed }} == 'true' ]; then
            echo "::set-output name=version::v${{ steps.check.outputs.version }}"
            echo "::set-output name=changed::true"
          else
            echo "::set-output name=version::${{ inputs.DEFAULT_VERSION }}"
            echo "::set-output name=changed::false"
          fi

      - name: Build and push Docker image
        id: docker_build_push
        uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.DOCKER_CONTEXT}}
          file: ${{ inputs.DOCKERFILE_PATH }}
          push: true
          tags: beclab/${{ inputs.PACKAGE_NAME }}:${{ steps.docker-tag.outputs.version }}
          build-args: ${{ inputs.DOCKER_BUILD_ARGS}}
          platforms: linux/amd64,linux/arm64
