name: Update AdminConsole Frontend

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
    branches:
      - 'main'
      - 'bug/fix-0729_beta'
    paths:
      - 'apps/adminConsole/package.json'
  push:
    branches:
      - 'main'
      - 'chore/apps'
    paths:
      - 'apps/adminConsole/**'
      - 'apps/common/**'
      - .github/workflows/update-admin-console.yml
      - .github/workflows/common-config.yml
      - nginx.conf

jobs:
  call-nodes-ci:
    uses: ./.github/workflows/common-config.yml
    with:
      NODE_VERSION: '16.14'
      PACKAGE_NAME: controlhub-demo
      PACKAGE_PATH: apps/adminConsole/package.json
      DIR_PATH: apps/adminConsole
      DOCKERFILE_PATH: Dockerfile-admin-console-client
      PACKAGE_BUILD_SCRIPT: DEMO=true yarn build:console
      DEFAULT_VERSION: latest
    secrets: inherit
