name: Build DevBox
on:
  workflow_dispatch:

  push:
    branches:
      - 'main'
      - 'feat/devbox'
    tags:
      - 'v*'
jobs:
  build-main:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: get latest tag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        id: get-latest-tag
        with:
          fallback: latest
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '18.14.2'
      - name: Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/packagge-lock.json')}}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install
        run: npm i -g yarn
      - run: yarn install --no-frozen-lockfile
      - name: Build
        run: yarn build:devbox
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: beclab/devbox:v_test_0.0.8
          file: Dockerfile-devbox-client
          platforms: linux/amd64,linux/arm64
